apiVersion: batch/v1
kind: CronJob
metadata:
  name: curl-random-cron
spec:
  # Runs every minute (adjust to "*/1 * * * *")
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-random
            image: quay.io/pknezevich/curl-cron:latest
            # Optional: if your script requires no parameters,
            # you can rely on the CMD set in the image.
            # Otherwise, you can override with:
            # command: ["/bin/bash", "/opt/curl-cron.sh"]
          restartPolicy: OnFailure

